exp_name: SPELL_VS_TVSum_default
model_name: SPELL
graph_name: TVSum_5_0
dataset: TVSum
loss_name: bce_logit
use_spf: False
use_ref: False
num_modality: 1
channel1: 256
channel2: 128
final_dim: 1
num_att_heads: 0
dropout: 0.5
lr: 0.02
wd: 0.0001
batch_size: 1
sch_param: 5
num_epoch: 50
sample_rate: 1
